server {
    listen 80;
    index index.php index.html;
    server_name tu_dominio.com; # O localhost

    # Backend API
    location /api {
        root /var/www/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        root /var/www/public;
        fastcgi_pass backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Frontend React
    location / {
        root /var/www/frontend; # Aquí es donde mapeamos el volumen en el compose
        try_files $uri $uri/ /index.html;
    }
}